# -*- coding: utf-8 -*-
"""process_annotations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8tUVwntZ1rBqEySfFIDrktIiS1osQJF
"""

import pandas as pd

def process_annotations(input_file, output_file, threshold=0.8):
    try:

        df = pd.read_csv(input_file)

        df_filtered = df[df['confidence_score'] >= threshold]

        df_disagreements = df[df['confidence_score'] < threshold]

        df_disagreements.to_csv("disagreements.log",index=False,header=True)

        df_filtered[['text', 'label']].to_json(output_file, orient='records', lines=True, force_ascii=False)

    except Exception as e:
        print(f"An error occured: {e}")

if __name__ == "__main__":
    process_annotations('raw_annotations.csv', 'clean_training_dataset.jsonl',threshold=0.8)

